Ecart/Ecart/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('search/', include('search.urls')),
    path('cart/', include("cart.urls")),
    path('register/', include('register.urls')),
    path('register/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecart/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('add/<int:product_id>/', views.addcart, name='add_cart'),
    path('', views.cart_detail, name="cart_detail"),
    path('remove/<int:id>/', views.remove, name="remove"),
    path('delete/<int:id>/', views.delete, name="delete"),
    path('checkout/', views.checkout, name='checkout'),
]

Ecart/register/urls.py
from django.urls import path, include
from . import views


app_name='register'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
]

Ecart/search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.search, name='searchable'),
]

Ecart/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.allCategory, name='allCategory'),
    path('<slug:c_slug>/', views.allCategory, name='products_category'),
    path('<slug:c_slug>/<slug:p_slug>/', views.productDetail, name='productDetails'),
]

Ecart/cart/models.py
from django.db import models
from store.models import Product

class Cart(models.Model):
    cartid = models.CharField(max_length=50, blank=True)
    date = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'cart'
        ordering = ['date']
        
    def __str__(self):
        return '{}'.format(self.cartid)
    
class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    
    class Meta:
        db_table = 'CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    
    def __str__(self):
        return '{}'.format(self.product)
    
    

# Create your models here.

Ecart/search/models.py
from django.db import models

# Create your models here.

Ecart/store/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='category')

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('store:products_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='product')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    availability = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('store:productDetails', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

# Create your models here.

Ecart/register/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

        
class SignUp(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
        
        

Ecart/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from store.models import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

def cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart
    
def addcart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cartid=cart_id(request))
    except ObjectDoesNotExist:
        cart = Cart.objects.create(
            cartid = cart_id(request)
        )
        cart.save()
    
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(requset, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cartid=cart_id(requset))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(requset, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def remove(request, id):
    cart = Cart.objects.get(cartid=cart_id(request))
    product = get_object_or_404(Product, id=id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
        
    return redirect('cart:cart_detail')

def delete(request, id):
    cart = Cart.objects.get(cartid=cart_id(request))
    product = get_object_or_404(Product, id=id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')
    
def checkout(request):
    return render(request, 'checkout.html')

Ecart/register/views.py
from django.shortcuts import render,redirect
from .forms import SignUp
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib import auth, messages


def signup(request):
    if request.method == 'POST':
        forms = SignUp(request.POST)
        if forms.is_valid():
            user = forms.save()
            login(request, user)
            return redirect('/store')   
    else:
        forms = SignUp()
    return render(request, 'registration/signup.html', {'forms': forms})

Ecart/search/views.py
from django.shortcuts import render
from django.db.models import Q
from store.models import Product


def search(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, "search.html", {'query': query, 'products': products})

Ecart/store/views.py
from django.shortcuts import render, get_object_or_404
from . models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage


def allCategory(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, availability=True)
    else:
        products_list = Product.objects.all().filter(availability = True)
        
    paginator = Paginator(products_list,6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(request, 'category.html', {'category':c_page, 'products':products})

def productDetail(request, c_slug, p_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=p_slug)
    except Exception as e:
        raise e
    return render(request, "product.html", {'product':product})


    

# Create your views here.

Ecart/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
    <!-- CSS only -->

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.7/css/all.css">

    <title>{% block title %}{% endblock title %}</title>

        
</head>
<body>
{% include 'header.html' %}
{% include 'navbar.html' %}
 
    {% block content %}

    {% endblock content %}
 
    {% include 'footer.html' %}
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>


  
</body>
</html>

Ecart/templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
<script src="https://kit.fontawesome.com/a076d05399.js"></script>

This is the cart page. Proceed toe review your items and place the order

{% endblock metadescription %}

{% block title %}
    Cart
{% endblock title %}
{% block content %}

{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center cart_title">Your Cart is Empty</h1>
        <br>
        <p class="text-center">Please Click <a href="{% url 'store:allCategory' %}"><button class="btn btn-primary">Here</button></a> to Shop with Us</p>
    </div>
</div>

{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center cart_title">Your Shopping Cart</h1>
        <br>
    </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table mytable">
            <thead class="myhead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}"></a>
                    </td>
                    <td class="text-lef">
                        {{cart_item.product.name}}
                        <br>
                        Price: ₹ {{cart_item.product.price}}
                        <br>
                        Qty: {{cart_item.quantity}} x  {{cart_item}}
                    </td>
                    <td>
                        ₹ {{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus" class='custom_icon'></i></a> 
                        &nbsp;
                        <a href="{% url 'cart:remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus" class='custom_icon'></i><a/>
                        &nbsp;
                        <a href="{% url 'cart:delete' cart_item.product.id %}" class='custom_a'><i class="fa fa-trash" class='custom_icon'></i><a/>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;
                        <a href="{% url 'cart:remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus" class='custom_icon'></i><a/>
                        &nbsp;
                        <a href="{% url 'cart:delete' cart_item.product.id %}" class='custom_a'><i class="fa fa-trash" class='custom_icon'></i><a/>
                    </td>
                    
                    
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table mytable">
        <thead class='myhead'>
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    Please Review your Shopping Cart Items Before Proceeding with the order Payment
                </td>
            </tr>
            <tr>
                <td>
                    Total Amount : <strong>{{total}}</strong>
                </td>
            </tr>
        </tbody>
    </table>
    {% if user.is_authenticated %}
    <div class="mx-auto">
        <a href="{% url 'cart:checkout' %}" class="btn btn-success">Buy now</a>
    </div>
    {% else %}
    <div class="mx-auto">
        <a href="/register/login" class="btn btn-success">Buy now</a>
    </div>
    {% endif %}
    <br><br>
    <div class="mx-auto">
        <a href="{% url 'store:allCategory' %}" class="btn btn-secondary">Continue Shopping</a>
    </div>
</div>

</div>
</div>
{% endif %}


{% endblock content %}

Ecart/templates/category.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}

{% if category %}
    {{category.description|truncatewords:155}}
{% else %}
    Welcome to Fruit store and can buy Loved items
{% endif %}
{% endblock metadescription %}

{% block title %}

{% if category %}
    {{category.name}}
{% endif %}

{% endblock title %}

{% block content %}

        <div>
            {% if category %}
                <img src="{{category.image.url}}" alt="{{category.name}}"  style="width: 100%";>
        </div>
        <br>
        <div>
            <h1>{{category.name}}</h1>
            <p>{{category.description}}</p>

        </div>
    {% else %}
        <div>
            <img src={% static 'img/vegetable.jpg' %} alt="our products" width='100%'>
        </div>
        <br>
        <div>
            <h1>Our Products Collection</h1>
            <p class="text-center">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        </div>
    {% endif %}
         <div class="container-lg">
                <div class="row">
                        {% for i in products %}         
                        <div class="card" style="width: 20rem;">
                            <a href="{{i.get_url}}"> <img src="{{i.image.url}}" class="card-img-top" alt="{{i.name}}"></a>
                                <div class="card-body">
                                    <h5 class="card-title">{{i.name}}</h5>
                                    <p class="card-text">₹{{i.price}}</p>
                                </div>
                        </div>
                        {% endfor %}
                    </div>  
                    <div class="mx-auto">
                        {% if products.paginator.num_pages > 1 %}
                        
                        
                        <hr>
                        <div class="text-center">
                            {% for pg in products.paginator.page_range %}
                            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                            {% endfor %}
                        </div>
                        {% endif %} 
                    </div>
                    <br>
                </div>
                              
            
{% endblock content %}

Ecart/templates/checkout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Checkout</title>
</head>
<body>
    {% load static %}

    <div class="mx-auto">
        <div class="text-center logo">
            <a href="/store">
            <img src="{% static 'img/organic.png' %}" alt="" width=300 >
            </a>
        </div>
    </div>
    <div class="container">
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
              <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-primary">Your cart</span>
                {% if item_count > 0 %}
                <span class="badge bg-primary rounded-pill">{{item_count}}</span>
              </h4>
              {% endif %}
              <ul class="list-group mb-3">
                <li class="list-group-item d-flex justify-content-between lh-sm">
                  <!--<div>
                    
                    <h6 class="my-0">Product name</h6>
                    <small class="text-muted">Brief description</small>
                  </div>
                  <span class="text-muted">$12</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                  <div>
                    <h6 class="my-0">Second product</h6>
                    <small class="text-muted">Brief description</small>
                  </div>
                  <span class="text-muted">$8</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                  <div>
                    <h6 class="my-0">Third item</h6>
                    <small class="text-muted">Brief description</small>
                  </div>
                  <span class="text-muted">$5</span>
                </li>
                <li class="list-group-item d-flex justify-content-between bg-light">
                  <div class="text-success">
                    <h6 class="my-0">Promo code</h6>
                    <small>EXAMPLECODE</small>
                  </div>
                  <span class="text-success">−$5</span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                  <span>Total (INR)</span>
                  <strong>${{total}}</strong>
                </li>
              </ul>-->
              <script>
                function myFunction(){
                    alert("Invalid PromoCode")
                }
              </script>
              <form class="card p-2">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Promo code">
                  <button type="submit" onclick="myFunction()" class="btn btn-secondary">Redeem</button>
                </div>
              </form>
            </div>
            <div class="col-md-7 col-lg-8">
              <h4 class="mb-3">Billing address</h4>
              <form class="needs-validation" novalidate="">
                <div class="row g-3">
                  <div class="col-sm-6">
                    <label for="firstName" class="form-label">First name</label>
                    <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
                    <div class="invalid-feedback">
                      Valid first name is required.
                    </div>
                  </div>
      
                  <div class="col-sm-6">
                    <label for="lastName" class="form-label">Last name</label>
                    <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
                    <div class="invalid-feedback">
                      Valid last name is required.
                    </div>
                  </div>
      
                  <div class="col-12">
                    <label for="username" class="form-label">Username</label>
                    <div class="input-group has-validation">
                      <span class="input-group-text">@</span>
                      <input type="text" class="form-control" id="username" placeholder="Username" required="">
                    <div class="invalid-feedback">
                        Your username is required.
                      </div>
                    </div>
                  </div>
      
                  <div class="col-12">
                    <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
                    <input type="email" class="form-control" id="email" placeholder="you@example.com">
                    <div class="invalid-feedback">
                      Please enter a valid email address for shipping updates.
                    </div>
                  </div>
      
                  <div class="col-12">
                    <label for="address" class="form-label">Address</label>
                    <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="">
                    <div class="invalid-feedback">
                      Please enter your shipping address.
                    </div>
                  </div>
      
                  <div class="col-12">
                    <label for="address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
                    <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
                  </div>
      
                  <!--<div class="col-md-5">
                    <label for="country" class="form-label">Country</label>
                    <select class="form-select" id="country" required="">
                      <option value="">Choose...</option>
                      <option>United States</option>
                    </select>
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
      
                  <div class="col-md-4">
                    <label for="state" class="form-label">State</label>
                    <select class="form-select" id="state" required="">
                      <option value="">Choose...</option>
                      <option>California</option>
                    </select>
                    <div class="invalid-feedback">
                      Please provide a valid state.
                    </div>
                  </div>-->
      
                  <div class="col-md-3">
                    <label for="zip" class="form-label">Zip</label>
                    <input type="text" class="form-control" id="zip" placeholder="" required="">
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>
      
                <hr class="my-4">
      
                <div class="form-check">
                  <input type="checkbox" class="form-check-input" id="same-address">
                  <label class="form-check-label" for="same-address">Shipping address is the same as my billing address</label>
                </div>
      
                <div class="form-check">
                  <input type="checkbox" class="form-check-input" id="save-info">
                  <label class="form-check-label" for="save-info">Save this information for next time</label>
                </div>
      
                <hr class="my-4">
      
                <h4 class="mb-3">Payment</h4>
      
                <div class="my-3">
                  <div class="form-check">
                    <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked="" required="">
                    <label class="form-check-label" for="credit">Credit card</label>
                  </div>
                  <div class="form-check">
                    <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required="">
                    <label class="form-check-label" for="debit">Debit card</label>
                  </div>
                  <div class="form-check">
                    <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required="">
                    <label class="form-check-label" for="paypal">PayPal</label>
                  </div>
                </div>
      
                <div class="row gy-3">
                  <div class="col-md-6">
                    <label for="cc-name" class="form-label">Name on card</label>
                    <input type="text" class="form-control" id="cc-name" placeholder="" required="">
                    <small class="text-muted">Full name as displayed on card</small>
                    <div class="invalid-feedback">
                      Name on card is required
                    </div>
                  </div>
      
                  <div class="col-md-6">
                    <label for="cc-number" class="form-label">Credit card number</label>
                    <input type="text" class="form-control" id="cc-number" placeholder="" required="">
                    <div class="invalid-feedback">
                      Credit card number is required
                    </div>
                  </div>
      
                  <div class="col-md-3">
                    <label for="cc-expiration" class="form-label">Expiration</label>
                    <input type="text" class="form-control" id="cc-expiration" placeholder="" required="">
                    <div class="invalid-feedback">
                      Expiration date required
                    </div>
                  </div>
      
                  <div class="col-md-3">
                    <label for="cc-cvv" class="form-label">CVV</label>
                    <input type="text" class="form-control" id="cc-cvv" placeholder="" required="">
                    <div class="invalid-feedback">
                      Security code required
                    </div>
                  </div>
                </div>
      
                <hr class="my-4 text-center">
                <div class='text-center'>
                    <button class="text-center w-50 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
                </div>
              </form>
            </div>
          </div>
    </div>
    <div class="footer">
        <p class="text-center">&copy; OrganicVictuals Pvt ltd</p>
    </div>
</body>
</html>

Ecart/templates/footer.html
<div class="foot">
    <p class="text-center">&copy; OrganicVictuals Pvt ltd</p>
</div>

Ecart/templates/header.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<div class="container-fluid">
    <div class="text-center logo">
        <a href="/store">
        <img src="{% static 'img/organic1.png' %}" alt="" width=300 >
        </a>
    </div>
</div>

Ecart/templates/navbar.html
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">


<nav class="navbar navbar-expand-lg  bg-light">
  <div class="container-fluid">
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'store:allCategory' %}"> <b>Welcome {{user.username}}</b></a>
    {% else %}
    <a class="navbar-brand" href="{% url 'store:allCategory' %}"> <b></b></a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'store:allCategory' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
          </a>
          <ul class="dropdown-menu"> 
        {% for i in links %}
        <li class="nav-item">
          <a class="nav-link" href="{{i.get_url}}">{{i.name}}</a>
        </li>
        {% endfor %}
        </ul>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="/register/logout">Logout</a>
          
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/register/login">Login</a>
        </li>
        {% endif %}
        
      </ul>
      <form class="d-flex" action="{% url 'search:searchable' %}" role="search" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

Ecart/templates/product.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}

    {{product.description|truncatewords:155}}

{% endblock metadescription %}

{% block title %}

{% if category %}
    {{product.name}}
{% endif %}

{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width: 20rem; margin-top:10%">
                <img src="{{product.image.url}}" alt="{{product.name}}">
            </div>
        </div>    


    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
        <h1 class="product_title">{{product.name}}</h1>
        <p><b>₹{{product.price}}</b></p>
        <h4 class="my_title">Product Description</h4>
        <p class="text-justify my_text">{{product.description}}</p>
        {% if product.stock <= 0 %}
            <p class="text-justify my_text"><b>Out of Stock</b></p>
        {% else %}
            <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-success">Add to Cart</a>
        {% endif %}
    
    </div>
</div>
</div>
</div>

{% endblock content %}